# These are supported funding model platforms

github: [zwanski2019] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: mohamed_zwanski # Replace with a single Patreon username
open_collective: mohamed-zwanski # Replace with a single Open Collective username
ko_fi: zwanski2019 # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: zwanski2019 # Replace with a single Liberapay username
issuehunt: zwanski2019 # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: zwanski2019 # Replace with a single Polar username
buy_me_a_coffee: zwanski2019 # Replace with a single Buy Me a Coffee username
custom: ['https://link1.com', 'https://link2.com', 'https://link3.com', 'https://link4.com'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
